services:
  juice-shop:
    container_name: juice-shop
    image: bkimminich/juice-shop:latest
    ports:
      - "80:3000"

  dastardly:
    container_name: dastardly
    build:
      context: .
      dockerfile: ./Dockerfile.dastardly
    depends_on:
      - juice-shop
    volumes:
      - .:/report/
    environment:
      - DASTARDLY_TARGET_URL=http://juice-shop:3000
      - DASTARDLY_OUTPUT_FILE=/report/dastardly-report.xml